In [3]:
import numpy as np
from numpy import *

***showing shape and type of numpy array***

In [5]:
a = array([[1,2,3],[4,5,6]])

In [6]:
a.shape

(2, 3)

***The array types bool , int , complex , float , object , unicode , and str a***

In [7]:
a.dtype

dtype('int64')

*** Basic indexing (slicing)***

In [10]:
a = arange(60).reshape(3,4,5);
print(a)


[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]
  [30 31 32 33 34]
  [35 36 37 38 39]]

 [[40 41 42 43 44]
  [45 46 47 48 49]
  [50 51 52 53 54]
  [55 56 57 58 59]]]


In [11]:
a = arange(6,10)
print(a)

[6 7 8 9]


***creating array from scratch***

In [13]:
np.zeros(10,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [14]:
#creating a multi dimensional array
np.ones([2,3],dtype=int)

array([[1, 1, 1],
       [1, 1, 1]])

In [17]:
np.full([2,3],3.14)

array([[3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14]])

In [16]:
np.arange(1,50,5)

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46])

In [18]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [19]:
np.random.random((3,3))

array([[0.95488021, 0.56518292, 0.65175342],
       [0.47635485, 0.61229812, 0.89090366],
       [0.91455024, 0.46677533, 0.21516334]])

In [21]:
np.random.randint(0,10,(3,3))

array([[5, 7, 9],
       [4, 7, 4],
       [7, 1, 5]])

In [22]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [25]:
np.empty((4,3))

array([[3.23095375e-316, 2.16443571e-312, 2.29175545e-312],
       [8.48798317e-313, 1.06099790e-312, 1.08221785e-312],
       [9.33678148e-313, 9.76118064e-313, 1.10343781e-312],
       [2.33419537e-312, 8.70018275e-313, 0.00000000e+000]])