In [4]:
import numpy as np
from numpy import *


Numpy Array Attributes

In [5]:
np.random.seed(0) #reproducibility

In [6]:
x1 = np.random.randint(10,size=6) #one dimensional Array
x2 = np.random.randint(10,size=(2,3)) #two dimensional Array
x3 = np.random.randint(10,size=(4,5,6)) #three dimensional array

In [9]:
print("x3:", x3.ndim) #shows number of dimension
print("x3:", x3.shape)#shows shape of array
print("x3:", x3.size) #shows size of array
print("itemsize:", x3.itemsize) #shows size of a element
print("nbytes:", x3.nbytes) #shows number of bytes of  array


x3: 3
x3: (4, 5, 6)
x3: 120
itemsize: 8
nbytes: 960


***Array Indexing ,Accessing Array Elements***

In [10]:
x1

array([5, 0, 3, 3, 7, 9])

In [11]:
x1[:3]

array([5, 0, 3])

In [12]:
x1[3:]

array([3, 7, 9])

In [13]:
x1[:-1]

array([5, 0, 3, 3, 7])

In [14]:
x1[-1:]

array([9])

In [15]:
x1[::2]

array([5, 3, 7])

In [16]:
x1[1::2]

array([0, 3, 9])

In [17]:
#reverse a array
x1[::-1]

array([9, 7, 3, 3, 0, 5])

***MultiDimensional Array***

In [18]:
x2


array([[3, 5, 2],
       [4, 7, 6]])

In [22]:
x2 = np.random.randint(0,19,(4,5))
x2

array([[11,  6, 15,  1, 12],
       [ 3, 18, 15,  3, 10],
       [12,  6,  3,  5, 11],
       [ 0, 11,  8, 10, 11]])

In [24]:
x2[:2,:3] # 2*3 array

array([[11,  6, 15],
       [ 3, 18, 15]])

In [26]:
x2[:3,::2] #all rows , every other column

array([[11, 15, 12],
       [ 3, 15, 10],
       [12,  3, 11]])

In [27]:
#reversing multidimensional array
x2[::-1,::-1]

array([[11, 10,  8, 11,  0],
       [11,  5,  3,  6, 12],
       [10,  3, 15, 18,  3],
       [12,  1, 15,  6, 11]])

In [28]:
#subarray as no copies
print(x2)

[[11  6 15  1 12]
 [ 3 18 15  3 10]
 [12  6  3  5 11]
 [ 0 11  8 10 11]]


In [29]:
x2_sub = x2[:2,:2]
print(x2_sub)

[[11  6]
 [ 3 18]]


In [30]:
x2_sub[0,0] = 99
print(x2_sub)

[[99  6]
 [ 3 18]]


In [31]:
print(x2) #it will affect the original array

[[99  6 15  1 12]
 [ 3 18 15  3 10]
 [12  6  3  5 11]
 [ 0 11  8 10 11]]


# sub array with copy function

In [34]:
x2_sub_copy = x2[:2,:2].copy()
print(x2_sub_copy)

[[99  6]
 [ 3 18]]


In [35]:
x2_sub_copy[0,0] = 64
print(x2_sub_copy) 

[[64  6]
 [ 3 18]]


In [37]:
print(x2) #it does not affect the original array

[[99  6 15  1 12]
 [ 3 18 15  3 10]
 [12  6  3  5 11]
 [ 0 11  8 10 11]]


## ***Reshaping of Array***

In [39]:
grid = np.arange(1,10)
grid

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
grid = grid.reshape((3,3))
grid

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [42]:
x = np.array([1,2,3])
x.reshape((1,3))

array([[1, 2, 3]])

In [43]:
np.expand_dims(x,0)

array([[1, 2, 3]])

In [44]:
x[np.newaxis,:]

array([[1, 2, 3]])

#Array Concatination and splitting

In [45]:
x = np.array([1,2,3]) 
y = np.array([4,5,6])
np.concatenate([x,y])

array([1, 2, 3, 4, 5, 6])

In [47]:
grid = np.array([[1,2,3],[4,5,6]])
np.concatenate([grid,grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [48]:
np.concatenate([grid,grid],axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [49]:
#vertically stack the arrays
np.vstack([x,grid])

array([[1, 2, 3],
       [1, 2, 3],
       [4, 5, 6]])

***Spiltting of  array***

In [56]:
x = [1,2,3,4,5,6,7,8,34,56,64]
y1,y2,y3 = np.split(x,[3,5])
print(y1,y2,y3)

[1 2 3] [4 5] [ 6  7  8 34 56 64]


In [57]:
grid = np.arange(16).reshape([4,4])
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [58]:
upper,lower = np.vsplit(grid,[2])
print(upper)

[[0 1 2 3]
 [4 5 6 7]]


In [59]:
print(lower)

[[ 8  9 10 11]
 [12 13 14 15]]


In [60]:
left,right = np.hsplit(grid,[2])
print(left)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]
